/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Engine: typeof import('@babylonjs/core')['Engine']
  const FreeCamera: typeof import('@babylonjs/core')['FreeCamera']
  const HemisphericLight: typeof import('@babylonjs/core')['HemisphericLight']
  const MeshBuilder: typeof import('@babylonjs/core')['MeshBuilder']
  const Scene: typeof import('@babylonjs/core')['Scene']
  const Vector2: typeof import('@babylonjs/core')['Vector2']
  const Vector3: typeof import('@babylonjs/core')['Vector3']
  const Vector4: typeof import('@babylonjs/core')['Vector4']
}
